### ISSUE TITLE
Split the compiler into smaller modules

### ISSUE THREAD

**Issue by MicheleBertoli** [cef62/css-modules-compiler#19]
The `compiler` is supposed to only compose the submodules but at the moment it has some logic inside and it counts more than 100 lines.
We should split it into smaller (and more testable) submodules.

My idea:

**transformer**
convertCssMapToAst
convertCssMapToAstMap

**utils**
updateFilesystem
cleanCss
concatenateCss
copySourceFolder

**optimizer**
clearJsonMap

Any thoughts @cef62?
More than happy to do it but I want your ok to proceed : )

**Comment by cef62** [comment]
Sounds perfect to me @MicheleBertoli ! Feel free to proceed 😎
