### ISSUE TITLE
Module Requirements

### ISSUE THREAD

**Issue by cef62** [cef62/css-modules-compiler#2]
This thread will be used to discuss initial goals and requirements for the compiler. The list of features will be used to design the compiler.

**Comment by MicheleBertoli** [comment]
This is what we want to achieve:

### Input

**src/button.js**

``` jsx
import React from 'react'

import styles from './button.css'

export default () => <button className={styles.button}>Yo</button>
```

**src/button.css**

``` css
.button {
  color: red;
}
```

![giphy](https://cloud.githubusercontent.com/assets/1308971/16259977/16fb15ba-385d-11e6-80af-be6f44be7db1.gif)

### Output

**dist/button.js**

``` jsx
import React from 'react'

const styles = {
  "button": "_button_lecme_1"
}

export default () => <button className={styles.button}>Yo</button>
```

**dist/styles.css**

``` css
._button_lecme_1 {
  color: red;
}
```

**Comment by MicheleBertoli** [comment]
Something like [babel-plugin-css-modules-transform](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform) but without babel.
