### ISSUE TITLE
Make <source> the default param

### ISSUE THREAD

**Issue by MicheleBertoli** [cef62/css-modules-compiler#25]
I was about to start writing the docs for the `cli` when I realised that we should accept the source folder as the first parameter (without any flag), like:

`css-modules-compiler compile <source> [options]`

What do you think @cef62?

**Comment by cef62** [comment]
I think you're right. The only drawback I see is that `yargs` support unnamed parameters but is greedy taking all of them, but we can just take the first unnamed parameter if `source` is not defined explicitly.

Work on the docs using your proposal, I'll change the `cli-parser` ASAP
