### ISSUE TITLE
Cleaner file names

### ISSUE THREAD

**Issue by MicheleBertoli** [cef62/css-modules-compiler#8]
Wouldn't it be better to rename the files in the following way?

`src/css-modules-compiler.js` => `src/compiler.js`
`src/css-modules-extractor.js` => `src/extractor.js`
`src/update-css-modules-imports.js` => `src/update-imports.js` (or just `src/updater.js` for consistency)
`bin/css-module-compiler.js` => `bin/css-modules-compiler.js`

What do you think @cef62?

**Comment by cef62** [comment]
I think your naming is really better than the actual!
