### ISSUE TITLE
Remove console.*

### ISSUE THREAD

**Issue by MicheleBertoli** [cef62/css-modules-compiler#9]
We should avoid using `console.*` and  use a proper logger library that gets activated by a `verbose` or `debug` flag.

**Comment by cef62** [comment]
I totally agree! We already have `shelljs` module exposing `echo`, it's enough for you or do you prefer to add a library like [debug](https://www.npmjs.com/package/debug)?

**Comment by MicheleBertoli** [comment]
I was thinking about something like `debug`, and I would like to use colours and emojis as well :)
